server:
  port: 3000

db:
  type: 'postgres'
  port: 5432

jwt:
  expiresIn: 1d

redis:
  port: 6379
  host: 'localhost'

app:
  version: 1.0

spaces:
  endpoint: https://sfo3.digitaloceanspaces.com
  access_id: 
  secret_key: 
  bucket_name:
  region: sfo3